"""
GitHub/repository automation helpers for repo-agent workflows.

The first milestone uses environment-injected credentials and the GitHub REST
API directly so the orchestration layer stays independent from the eventual
GitHub App installation flow.
"""
from __future__ import annotations

import base64
import json
import os
import re
import shutil
import subprocess
import tempfile
import time
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path
from typing import Any

_TOKEN_ENV_NAMES = (
    "RINGTAIL_GITHUB_TOKEN",
    "GITHUB_TOKEN",
    "GH_TOKEN",
)


def resolve_github_token(explicit_token: str | None = None) -> str:
    if explicit_token:
        return explicit_token
    for name in _TOKEN_ENV_NAMES:
        value = os.environ.get(name, "")
        if value:
            return value
    return ""


def is_local_repo_url(repo_url: str) -> bool:
    if repo_url.startswith("file://"):
        return True
    if repo_url.startswith("http://") or repo_url.startswith("https://") or repo_url.startswith("git@"):
        return False
    return Path(repo_url).exists()


def parse_repo_slug(repo_url: str) -> tuple[str, str]:
    cleaned = repo_url.strip()
    if cleaned.endswith(".git"):
        cleaned = cleaned[:-4]
    match = re.search(r"github\.com[:/](?P<owner>[^/]+)/(?P<repo>[^/]+)$", cleaned)
    if not match:
        raise ValueError(f"Could not parse GitHub owner/repo from URL: {repo_url}")
    return match.group("owner"), match.group("repo")


def clone_repo(repo_url: str, destination_dir: str, base_branch: str | None = None, token: str | None = None) -> str:
    dest = Path(destination_dir)
    if dest.exists():
        shutil.rmtree(dest)
    dest.parent.mkdir(parents=True, exist_ok=True)

    command = ["git", "clone"]
    if base_branch:
        command.extend(["--branch", base_branch])
    command.extend(["--depth", "1", build_authenticated_clone_url(repo_url, token), str(dest)])
    _run_git(command)
    return str(dest)


def build_authenticated_clone_url(repo_url: str, token: str | None = None) -> str:
    if is_local_repo_url(repo_url):
        if repo_url.startswith("file://"):
            return repo_url
        return str(Path(repo_url).resolve())
    if not token:
        return repo_url

    owner, repo = parse_repo_slug(repo_url)
    return f"https://x-access-token:{token}@github.com/{owner}/{repo}.git"


def create_branch(repo_path: str, branch_name: str) -> None:
    _run_git(["git", "checkout", "-B", branch_name], cwd=repo_path)


def working_tree_has_changes(repo_path: str) -> bool:
    result = _run_git(["git", "status", "--porcelain"], cwd=repo_path, capture_output=True)
    return bool(result.stdout.strip())


def commit_all(repo_path: str, message: str) -> str:
    _run_git(["git", "add", "."], cwd=repo_path)
    if not working_tree_has_changes(repo_path):
        raise ValueError("No repository changes to commit")

    env = os.environ.copy()
    env.setdefault("GIT_AUTHOR_NAME", "Ringtail")
    env.setdefault("GIT_AUTHOR_EMAIL", "ringtail@local")
    env.setdefault("GIT_COMMITTER_NAME", env["GIT_AUTHOR_NAME"])
    env.setdefault("GIT_COMMITTER_EMAIL", env["GIT_AUTHOR_EMAIL"])
    _run_git(["git", "commit", "-m", message], cwd=repo_path, env=env)
    sha = _run_git(["git", "rev-parse", "HEAD"], cwd=repo_path, capture_output=True).stdout.strip()
    return sha


def push_branch(repo_path: str, repo_url: str, branch_name: str, token: str) -> None:
    if not token:
        raise EnvironmentError("GitHub token is required to push a branch")
    remote_url = build_authenticated_clone_url(repo_url, token)
    _run_git(["git", "push", remote_url, f"HEAD:refs/heads/{branch_name}"], cwd=repo_path)


def build_pr_body(
    *,
    prompt: str,
    target_summary: str,
    test_summary: str,
    performance_summary: str,
) -> str:
    return "\n".join(
        [
            "## Summary",
            f"- Prompt: {prompt}",
            f"- Selected target: {target_summary}",
            f"- Validation: {test_summary}",
            f"- Performance: {performance_summary}",
            "",
            "## Notes",
            "- Generated by Ringtail repo agent.",
        ]
    )


def create_pull_request(
    *,
    repo_url: str,
    title: str,
    body: str,
    head_branch: str,
    base_branch: str,
    token: str,
) -> dict[str, Any]:
    if not token:
        raise EnvironmentError("GitHub token is required to create a pull request")

    owner, repo = parse_repo_slug(repo_url)
    url = f"https://api.github.com/repos/{owner}/{repo}/pulls"
    payload = json.dumps(
        {
            "title": title,
            "head": head_branch,
            "base": base_branch,
            "body": body,
        }
    ).encode("utf-8")
    headers = {
        "Accept": "application/vnd.github+json",
        "Authorization": f"Bearer {token}",
        "X-GitHub-Api-Version": "2022-11-28",
        "User-Agent": "ringtail-repo-agent",
        "Content-Type": "application/json",
    }
    request = urllib.request.Request(url, data=payload, headers=headers, method="POST")
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            return json.loads(response.read().decode("utf-8"))
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"GitHub PR creation failed: {exc.code} {detail}") from exc


def make_branch_name(prefix: str = "ringtail") -> str:
    return f"{prefix}/optimize-{time.strftime('%Y%m%d-%H%M%S', time.gmtime())}"


def _run_git(
    command: list[str],
    *,
    cwd: str | None = None,
    env: dict[str, str] | None = None,
    capture_output: bool = False,
) -> subprocess.CompletedProcess[str]:
    result = subprocess.run(
        command,
        cwd=cwd,
        env=env,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(
            "git command failed: "
            + " ".join(command)
            + "\n"
            + (result.stderr or result.stdout or "").strip()
        )
    if capture_output:
        return result
    return result
